# Generated by Django 5.0.9 on 2026-04-24 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('whatsapp_number', models.CharField(max_length=30)),
                ('gateway_provider', models.CharField(choices=[('Picky Assist', 'Picky Assist'), ('Meta WhatsApp', 'Meta WhatsApp'), ('Other', 'Other')], default='Picky Assist', max_length=40)),
                ('trigger_keyword', models.CharField(max_length=40)),
                ('primary_language', models.CharField(choices=[('Odia', 'Odia'), ('Hindi', 'Hindi'), ('Bengali', 'Bengali'), ('Telugu', 'Telugu'), ('Tamil', 'Tamil'), ('English', 'English')], default='Odia', max_length=20)),
                ('secondary_language', models.CharField(blank=True, choices=[('Odia', 'Odia'), ('Hindi', 'Hindi'), ('Bengali', 'Bengali'), ('Telugu', 'Telugu'), ('Tamil', 'Tamil'), ('English', 'English')], default='English', max_length=20)),
                ('stt_provider', models.CharField(default='OpenAI Whisper', max_length=50)),
                ('tts_provider', models.CharField(default='OpenAI TTS', max_length=50)),
                ('translation_model', models.CharField(default='gpt-4o-mini', max_length=80)),
                ('rag_model', models.CharField(default='gpt-4o-mini', max_length=80)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Paused', 'Paused'), ('Disabled', 'Disabled')], default='Active', max_length=20)),
                ('welcome_message', models.TextField(blank=True)),
                ('webhook_url', models.CharField(blank=True, max_length=500)),
                ('messages_processed_count', models.IntegerField(default=0)),
                ('avg_response_time', models.FloatField(default=0.0)),
                ('success_rate', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('catalogue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hooks', to='catalogues.catalogue')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('gateway_provider', 'trigger_keyword')},
            },
        ),
    ]
