# Generated by Django 5.0.9 on 2026-04-24 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=63, unique=True)),
                ('description', models.TextField(blank=True)),
                ('geography', models.CharField(blank=True, default='All India', max_length=120)),
                ('season_year', models.CharField(blank=True, help_text='e.g. Kharif 2026', max_length=40)),
                ('vector_db_status', models.CharField(choices=[('NotBuilt', 'Not Built'), ('Building', 'Building'), ('Ready', 'Ready'), ('Failed', 'Failed')], default='NotBuilt', max_length=20)),
                ('vector_db_generated_at', models.DateTimeField(blank=True, null=True)),
                ('vector_db_chunks_count', models.IntegerField(default=0)),
                ('vector_db_error', models.TextField(blank=True)),
                ('embedding_model', models.CharField(blank=True, max_length=120)),
                ('vector_store_collection_name', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published')], default='Draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('documents', models.ManyToManyField(blank=True, related_name='catalogues', to='documents.document')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
