# Generated by Django 5.0.9 on 2026-04-24 02:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('keywords', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_key', models.CharField(db_index=True, editable=False, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_key', models.CharField(db_index=True, editable=False, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='documents.category')),
            ],
            options={
                'verbose_name_plural': 'Subcategories',
                'ordering': ['category__name', 'name'],
                'unique_together': {('category', 'name_key')},
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('title_key', models.CharField(db_index=True, editable=False, max_length=510, unique=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('file_path', models.CharField(blank=True, help_text='Original filename/path from CSV if file not uploaded', max_length=1000)),
                ('source_url', models.URLField(blank=True, max_length=1000)),
                ('crop', models.CharField(choices=[('Rice', 'Rice'), ('Wheat', 'Wheat'), ('Maize', 'Maize'), ('Pulses', 'Pulses'), ('Oilseeds', 'Oilseeds'), ('Vegetables', 'Vegetables'), ('Other', 'Other')], default='Rice', max_length=40)),
                ('content_type', models.CharField(choices=[('Advisory', 'Advisory'), ('Research Paper', 'Research Paper'), ('SOP / Practice', 'SOP / Practice'), ('FAQ', 'FAQ'), ('Policy', 'Policy')], default='Advisory', max_length=40)),
                ('doc_type', models.CharField(choices=[('Factsheet', 'Factsheet'), ('Research Article', 'Research Article'), ('Bulletin', 'Bulletin'), ('Training Manual', 'Training Manual'), ('Technical Manual', 'Technical Manual'), ('Booklet', 'Booklet'), ('PPT', 'PPT'), ('Other', 'Other')], default='Factsheet', max_length=60)),
                ('geography', models.CharField(blank=True, default='All India', max_length=120)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('authors', models.TextField(blank=True)),
                ('organizations', models.TextField(blank=True)),
                ('journal_or_book', models.CharField(blank=True, max_length=500)),
                ('countries', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('PendingReview', 'Pending Review'), ('Published', 'Published'), ('Unpublished', 'Unpublished')], default='Draft', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_on', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.category')),
                ('keywords', models.ManyToManyField(blank=True, related_name='documents', to='keywords.keyword')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.subcategory')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
