# Generated by Django 5.0.9 on 2026-05-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(db_index=True, help_text="Filename prefix shared by all images in this visual group (e.g. 'bacterial_leaf_blight').", max_length=120)),
                ('image', models.ImageField(upload_to='image_bank/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True, help_text='Visual description of what these images show. Loaded from <prefix>.txt sidecar at ingest time.')),
                ('embedding_dim', models.IntegerField(default=0)),
                ('indexed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['prefix', 'id'],
            },
        ),
    ]
