# Generated by Django 5.0.9 on 2026-05-08 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0001_initial'),
        ('image_bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgeimage',
            name='catalogue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_images', to='catalogues.catalogue'),
        ),
        migrations.AlterField(
            model_name='knowledgeimage',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='knowledgeimage',
            name='prefix',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.CreateModel(
            name='ImageGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(db_index=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('catalogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_groups', to='catalogues.catalogue')),
            ],
            options={
                'ordering': ['catalogue', 'prefix'],
                'unique_together': {('catalogue', 'prefix')},
            },
        ),
        migrations.AddField(
            model_name='knowledgeimage',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='image_bank.imagegroup'),
        ),
    ]
