# Generated by Django 5.0.9 on 2026-04-24 02:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogues', '0001_initial'),
        ('documents', '0001_initial'),
        ('hooks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=30)),
                ('district', models.CharField(blank=True, max_length=80)),
                ('trigger_keyword', models.CharField(blank=True, max_length=40)),
                ('category', models.CharField(blank=True, choices=[('Rice Variety', 'Rice Variety'), ('Disease', 'Disease'), ('Fertiliser', 'Fertiliser'), ('Water Mgmt', 'Water Mgmt'), ('Others', 'Others')], max_length=40)),
                ('task_type', models.CharField(blank=True, choices=[('Diagnosis', 'Diagnosis'), ('Variety Suitability', 'Variety Suitability'), ('Fertiliser Rec.', 'Fertiliser Recommendation'), ('Management Advice', 'Management Advice'), ('Other', 'Other')], max_length=40)),
                ('problem_entity', models.CharField(blank=True, max_length=200)),
                ('season', models.CharField(blank=True, choices=[('Kharif', 'Kharif'), ('Rabi', 'Rabi'), ('Zaid', 'Zaid')], max_length=20)),
                ('crop_stage', models.CharField(blank=True, choices=[('Nursery', 'Nursery'), ('Tillering', 'Tillering'), ('Flowering', 'Flowering'), ('Mature Grain', 'Mature Grain')], max_length=30)),
                ('missing_context', models.CharField(blank=True, max_length=500)),
                ('original_query_text', models.TextField(blank=True)),
                ('original_query_language', models.CharField(blank=True, default='Odia', max_length=30)),
                ('original_query_voice_file', models.FileField(blank=True, null=True, upload_to='audio/in/')),
                ('translated_query_text', models.TextField(blank=True)),
                ('ai_response_text', models.TextField(blank=True)),
                ('ai_response_text_local', models.TextField(blank=True)),
                ('ai_response_voice_file', models.FileField(blank=True, null=True, upload_to='audio/out/')),
                ('response_time_seconds', models.FloatField(default=0.0)),
                ('farmer_feedback', models.CharField(blank=True, choices=[('Good', 'Good'), ('Average', 'Average'), ('Bad', 'Bad')], max_length=10)),
                ('pipeline_trace', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('Received', 'Received'), ('Processing', 'Processing'), ('Responded', 'Responded'), ('Failed', 'Failed'), ('Escalated', 'Escalated'), ('Flagged', 'Flagged')], default='Received', max_length=20)),
                ('flagged_for_review', models.BooleanField(default=False)),
                ('review_notes', models.TextField(blank=True)),
                ('catalogue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queries', to='catalogues.catalogue')),
                ('hook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queries', to='hooks.hook')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_queries', to=settings.AUTH_USER_MODEL)),
                ('source_documents', models.ManyToManyField(blank=True, related_name='used_in_queries', to='documents.document')),
            ],
            options={
                'verbose_name_plural': 'Queries',
                'ordering': ['-timestamp'],
            },
        ),
    ]
