# Generated by Django 5.0.9 on 2026-05-08 15:04

import api_endpoints.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogues', '0001_initial'),
        ('queries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('token', models.CharField(db_index=True, default=api_endpoints.models._new_token, max_length=64, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('language', models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Odia', 'Odia'), ('Bengali', 'Bengali'), ('Telugu', 'Telugu'), ('Tamil', 'Tamil')], default='English', max_length=20)),
                ('user_type', models.CharField(choices=[('farmer', 'Farmer (short, plain-language)'), ('researcher', 'Researcher (detailed, technical)')], default='farmer', max_length=20)),
                ('sample_query', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('request_count', models.IntegerField(default=0)),
                ('last_called_at', models.DateTimeField(blank=True, null=True)),
                ('catalogue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_apis', to='catalogues.catalogue')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_apis', to=settings.AUTH_USER_MODEL)),
                ('source_query', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_apis', to='queries.query')),
            ],
            options={
                'verbose_name': 'Generated API',
                'verbose_name_plural': 'Generated APIs',
                'ordering': ['-created_at'],
            },
        ),
    ]
