# Generated by Django 5.0.9 on 2026-04-24 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('keyword_key', models.CharField(db_index=True, editable=False, max_length=255, unique=True)),
                ('parent_category', models.CharField(choices=[('Crop', 'Crop'), ('Disease', 'Disease'), ('Season', 'Season'), ('Region', 'Region'), ('Practice', 'Practice'), ('Fertiliser', 'Fertiliser'), ('Other', 'Other')], default='Crop', max_length=40)),
                ('subcategory', models.CharField(blank=True, max_length=255)),
                ('region', models.CharField(choices=[('All India', 'All India'), ('Odisha', 'Odisha'), ('Bihar', 'Bihar'), ('West Bengal', 'West Bengal'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Jharkhand', 'Jharkhand'), ('Chhattisgarh', 'Chhattisgarh'), ('Andhra Pradesh', 'Andhra Pradesh')], default='All India', max_length=80)),
                ('translation', models.CharField(blank=True, max_length=255)),
                ('language', models.CharField(choices=[('Odia', 'Odia'), ('Hindi', 'Hindi'), ('Bengali', 'Bengali'), ('Telugu', 'Telugu'), ('Tamil', 'Tamil'), ('Kannada', 'Kannada'), ('Marathi', 'Marathi'), ('Gujarati', 'Gujarati'), ('Punjabi', 'Punjabi'), ('English', 'English')], default='Odia', max_length=30)),
                ('local_names', models.TextField(blank=True, help_text='Comma-separated synonyms / local names / spellings.')),
                ('expert_validated', models.BooleanField(default=False)),
                ('validation_source', models.CharField(blank=True, choices=[('IRRI', 'IRRI'), ('Govt', 'Govt'), ('Research Paper', 'Research Paper'), ('Other', 'Other')], max_length=40)),
                ('image', models.ImageField(blank=True, null=True, upload_to='keywords/')),
                ('status', models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft'), ('Disabled', 'Disabled')], default='Published', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['keyword'],
            },
        ),
    ]
